site_name: "Orka"
site_description: "The OpenGL 4.6 Rendering Kernel in Ada 2012"
site_author: "onox"
site_url: "https://orka-engine.netlify.com"

repo_name: "onox/orka"
repo_url: "https://github.com/onox/orka"

# Disable edit button
edit_uri: ""

copyright: "Copyright &copy; 2016 - 2021 onox"

theme:
  name: "material"
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: white
      accent: "blue"
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    logo: material/shark-fin
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes

plugins:
  - search:
      lang:
        - en

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/onox
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/ada-lang/Lobby

markdown_extensions:
  - abbr
  - admonition
  - def_list
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: onox
      repo: orka
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.smartsymbols:
      copyright: false
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting started:
      - Installation: installation.md
  - Documentation:
      - Parallel programming: parallel-programming.md
      - Containers: containers.md
      - Logging: logging.md
      - Computing:
          - Introduction: computing/index.md
          - Algorithms: computing/algorithms.md
      - Rendering:
          - Introduction: rendering/index.md
          - Contexts: rendering/contexts.md
          - Windows and devices: rendering/windows-devices.md
          - Buffers: rendering/buffers.md
          - Vertex formats: rendering/vertex-formats.md
          - Programs: rendering/programs.md
          - Textures: rendering/textures.md
          - Framebuffers: rendering/framebuffers.md
          - Cameras: rendering/cameras.md
          - Effects: rendering/effects.md
          - Removed features: rendering/removed-features.md
      - Resources:
          - Locations: resources/locations.md
          - Loaders: resources/loaders.md
      - Transforms:
          - Vectors: transforms/vectors.md
          - Matrices: transforms/matrices.md
          - Quaternions: transforms/quaternions.md
          - Scene trees: transforms/scene-trees.md
      - Numerics:
          - Integrators: numerics/integrators.md
          - Tensors:
              - Introduction: numerics/tensors/index.md
              - Shape and dimensions: numerics/tensors/shape-and-dimensions.md
              - Creating tensors: numerics/tensors/creating-tensors.md
              - Element-wise operations: numerics/tensors/element-wise-operations.md
              - Matrix operations: numerics/tensors/matrix-operations.md
              - Expressions: numerics/tensors/expressions.md
              - Indexing: numerics/tensors/indexing.md
              - Statistics: numerics/tensors/statistics.md
          - Filtering: numerics/filtering.md
      - Plug-ins:
          - Archives: plugins/archives.md
          - Atmosphere: plugins/atmosphere.md
          - glTF: plugins/gltf.md
          - Terrain: plugins/terrain.md
  - Contributing: contributing.md
