site_name: "Orka"
site_description: "The OpenGL 4.6 Rendering Kernel in Ada 2012"
site_author: "onox"
site_url: "https://orka-engine.netlify.com"

repo_name: "onox/orka"
repo_url: "https://github.com/onox/orka"

# Disable edit button
edit_uri: ""

copyright: "Copyright &copy; 2016 - 2021 onox"

theme:
  name: "material"
  palette:
    primary: "indigo"
    accent: "blue"
  logo:
    icon: "🌌"

plugins:
  - search
  - minify:
      minify_html: true

extra:
  search:
    language: "en"
  social:
    - type: "github"
      link: "https://github.com/onox"

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: onox
      repo: orka
  - pymdownx.superfences
  - pymdownx.smartsymbols:
      copyright: false
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

nav:
  - Orka: index.md
  - Installation: installation.md
  - Contexts: contexts.md
  - Parallel programming: parallel-programming.md
  - Containers: containers.md
  - Logging: logging.md
  - GPGPU: gpgpu.md
  - Rendering:
      - Introduction: rendering/index.md
      - Buffers: rendering/buffers.md
      - Vertex formats: rendering/vertex-formats.md
      - Programs: rendering/programs.md
      - Textures: rendering/textures.md
      - Framebuffers: rendering/framebuffers.md
      - Cameras: rendering/cameras.md
      - Effects: rendering/effects.md
  - Resources:
      - Locations: resources/locations.md
      - Loaders: resources/loaders.md
  - Transforms:
      - Vectors: transforms/vectors.md
      - Matrices: transforms/matrices.md
      - Quaternions: transforms/quaternions.md
      - Scene trees: transforms/scene-trees.md
  - Tensors: numerics/tensors.md
  - Plug-ins:
      - Archives: plugins/archives.md
      - Atmosphere: plugins/atmosphere.md
      - glTF: plugins/gltf.md
      - Terrain: plugins/terrain.md
  - Contributing: contributing.md
