name = "orka_numerics"
description = "Tensors (multidimensional arrays) and integrators"
version = "1.0.0"
website = "https://github.com/onox/orka"
licenses = "Apache-2.0"
tags = ["orka", "math", "vector", "matrix", "ndarray", "tensor", "numpy", "integration", "rk4", "kalman", "optimization", "leastsquares", "linearalgebra", "linalg"]

authors = ["onox"]
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]

[build-switches]
validation.compile_checks = "warnings"
"*".style_checks = ["-gnatygAO-Is"]

[gpr-externals]
ORKA_NUMERICS_SIMD_TYPE = ["SSE4.1", "AVX", "AVX2"]

[gpr-set-externals]
ORKA_NUMERICS_SIMD_TYPE = "SSE4.1"

[[depends-on]]
orka_simd = "^1.0.0"
orka_types = "^1.0.0"

[[pins]]
orka_simd = { path = "../orka_simd" }
orka_types = { path = "../orka_types" }
