name = "orka"
description = "OpenGL 4.6 rendering kernel written in Ada 2012"
version = "0.2.0"
website = "https://github.com/onox/orka"
licenses = "Apache-2.0"
tags = ["azdo", "egl", "opengl", "orka", "rendering", "graphics", "ktx", "gltf"]

authors = ["onox"]
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]

[gpr-set-externals.'case(os)']
linux = { ALR_OS = "linux" }
windows = { ALR_OS = "windows" }

[project-files.'case(os)']
linux = ["orka.gpr", "orka-egl.gpr"]
windows = ["orka.gpr"]

[available.'case(os)']
linux = true
windows = true
'...' = false

[[depends-on]]
orka_types = "^1.0.0"
orka_simd = "^1.0.0"
orka_transforms = "^1.0.0"

[[depends-on]]
[depends-on.'case(os)'.linux]
orka_egl = "^1.0.0"
