name = "orka_examples"
description = "Examples for the Orka rendering kernel"
version = "1.0.0"
website = "https://github.com/onox/orka"
licenses = "Apache-2.0"
tags = ["opengl", "orka"]

authors = ["onox"]
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]

executables = [
    "orka_1_triangle",
    "orka_3_module_array",
    "orka_4_mdi",
    "orka_5_scene_tree",
    "orka_6_fft",
    "orka_7_half",
    "orka_9_jobs",
    "orka_10_compute",
    "orka_11_instancing",
    "orka_12_stencil",
    "orka_13_geometry"
]

[build-switches]
validation.compile_checks = "warnings"
"*".style_checks = ["-gnatygAOM99-Is"]

[[depends-on]]
orka_awt = "^1.0.0"

[[pins]]
orka_awt = { path = "../orka_awt" }
