--  Copyright (c) 2016 onox <denkpadje@gmail.com>
--
--  Licensed under the Apache License, Version 2.0 (the "License");
--  you may not use this file except in compliance with the License.
--  You may obtain a copy of the License at
--
--      http://www.apache.org/licenses/LICENSE-2.0
--
--  Unless required by applicable law or agreed to in writing, software
--  distributed under the License is distributed on an "AS IS" BASIS,
--  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
--  See the License for the specific language governing permissions and
--  limitations under the License.

private package GL.Functions is
   pragma Preelaborate;

   type String_Access is not null access constant String;

   type Reference_ID is
     (GL_Active_Shader_Program,
      GL_Attach_Shader,
      GL_Begin_Conditional_Render,
      GL_Begin_Query_Indexed,
      GL_Begin_Transform_Feedback,
      GL_Bind_Attrib_Location,
      GL_Bind_Buffer,
      GL_Bind_Buffer_Base,
      GL_Bind_Buffer_Range,
      GL_Bind_Framebuffer,
      GL_Bind_Program_Pipeline,
      GL_Bind_Renderbuffer,
      GL_Bind_Sampler,
      GL_Bind_Samplers,
      GL_Bind_Texture_Unit,
      GL_Bind_Transform_Feedback,
      GL_Bind_Vertex_Array,
      GL_Blend_Color,
      GL_Blend_Equation,
      GL_Blend_Equationi,
      GL_Blend_Equation_Separate,
      GL_Blend_Funci,
      GL_Blend_Func_Separate,
      GL_Blit_Named_Framebuffer,
      GL_Check_Named_Framebuffer_Status,
      GL_Clamp_Color,
      GL_Clear_Named_Framebufferfi,
      GL_Clear_Named_Framebufferfv,
      GL_Clear_Named_Framebufferiv,
      GL_Compile_Shader,
      GL_Compressed_Texture_Sub_Image_1D,
      GL_Compressed_Texture_Sub_Image_2D,
      GL_Compressed_Texture_Sub_Image_3D,
      GL_Copy_Named_Buffer_Sub_Data,
      GL_Copy_Texture_Sub_Image_1D,
      GL_Copy_Texture_Sub_Image_2D,
      GL_Copy_Texture_Sub_Image_3D,
      GL_Create_Buffers,
      GL_Create_Framebuffers,
      GL_Create_Program,
      GL_Create_Program_Pipelines,
      GL_Create_Queries,
      GL_Create_Renderbuffers,
      GL_Create_Samplers,
      GL_Create_Shader,
      GL_Create_Shader_Programv,
      GL_Create_Textures,
      GL_Create_Transform_Feedbacks,
      GL_Create_Vertex_Arrays,
      GL_Delete_Buffers,
      GL_Delete_Framebuffers,
      GL_Delete_Program,
      GL_Delete_Program_Pipelines,
      GL_Delete_Queries,
      GL_Delete_Samplers,
      GL_Delete_Shader,
      GL_Delete_Transform_Feedbacks,
      GL_Delete_Vertex_Arrays,
      GL_Disable_Vertex_Array_Attrib,
      GL_Draw_Arrays_Instanced,
      GL_Draw_Arrays_Instanced_Base_Instance,
      GL_Draw_Elements_Base_Vertex,
      GL_Draw_Elements_Instanced,
      GL_Draw_Elements_Instanced_Base_Instance,
      GL_Draw_Elements_Instanced_Base_Vertex,
      GL_Draw_Elements_Instanced_Base_Vertex_Base_Instance,
      GL_Draw_Transform_Feedback,
      GL_Draw_Transform_Feedback_Instanced,
      GL_Draw_Transform_Feedback_Stream,
      GL_Draw_Transform_Feedback_Stream_Instanced,
      GL_Enable_Vertex_Array_Attrib,
      GL_End_Conditional_Render,
      GL_End_Query_Indexed,
      GL_End_Transform_Feedback,
      GL_Flush_Mapped_Named_Buffer_Range,
      GL_Generate_Texture_Mipmap,
      GL_Get_Attached_Shaders,
      GL_Get_Attrib_Location,
      GL_Get_Named_Buffer_Parameteriv,
      GL_Get_Named_Buffer_Pointerv,
      GL_Get_Named_Buffer_Sub_Data,
      GL_Get_Named_Framebuffer_Parameteriv,
      GL_Get_Named_Renderbuffer_Parameteriv,
      GL_Get_Program_Info_Log,
      GL_Get_Program_Interfaceiv,
      GL_Get_Programiv,
      GL_Get_Program_Pipeline_Info_Log,
      GL_Get_Program_Pipelineiv,
      GL_Get_Program_Resource_Index,
      GL_Get_Program_Resourceiv,
      GL_Get_Program_Resource_Location,
      GL_Get_Program_Resource_Location_Index,
      GL_Get_Program_Resource_Name,
      GL_Get_Program_Stageiv,
      GL_Get_Query_Indexed,
      GL_Get_Query_Objectiv,
      GL_Get_Query_Objectuiv,
      GL_Get_Sampler_Parameterfv,
      GL_Get_Sampler_Parameteriv,
      GL_Get_Shader_Info_Log,
      GL_Get_Shaderiv,
      GL_Get_Shader_Source,
      GL_Get_Stringi,
      GL_Get_Texture_Level_Parameteriv,
      GL_Get_Texture_Parameterfv,
      GL_Get_Texture_Parameteriv,
      GL_Get_Uniform_Location,
      GL_Get_Uniform_Subroutineuiv,
      GL_Invalidate_Buffer_Data,
      GL_Invalidate_Buffer_Sub_Data,
      GL_Invalidate_Named_Framebuffer_Data,
      GL_Invalidate_Named_Framebuffer_Sub_Data,
      GL_Invalidate_Tex_Image,
      GL_Invalidate_Tex_Sub_Image,
      GL_Link_Program,
      GL_Map_Named_Buffer,
      GL_Map_Named_Buffer_Range,
      GL_Memory_Barrier,
      GL_Memory_Barrier_By_Region,
      GL_Multi_Draw_Arrays,
      GL_Multi_Draw_Arrays_Indirect,
      GL_Multi_Draw_Elements,
      GL_Multi_Draw_Elements_Base_Vertex,
      GL_Multi_Draw_Elements_Indirect,
      GL_Named_Buffer_Data,
      GL_Named_Buffer_Storage,
      GL_Named_Buffer_Sub_Data,
      GL_Named_Framebuffer_Draw_Buffer,
      GL_Named_Framebuffer_Draw_Buffers,
      GL_Named_Framebuffer_Parameteri,
      GL_Named_Framebuffer_Read_Buffer,
      GL_Named_Framebuffer_Renderbuffer,
      GL_Named_Framebuffer_Texture,
      GL_Named_Framebuffer_Texture_Layer,
      GL_Named_Renderbuffer_Storage,
      GL_Named_Renderbuffer_Storage_Multisample,
      GL_Pause_Transform_Feedback,
      GL_Program_Parameteri,
      GL_Program_Uniform_1i,
      GL_Program_Uniform_1iv,
      GL_Program_Uniform_2i,
      GL_Program_Uniform_2iv,
      GL_Program_Uniform_3i,
      GL_Program_Uniform_3iv,
      GL_Program_Uniform_4i,
      GL_Program_Uniform_4iv,
      GL_Program_Uniform_1ui,
      GL_Program_Uniform_1uiv,
      GL_Program_Uniform_2ui,
      GL_Program_Uniform_2uiv,
      GL_Program_Uniform_3ui,
      GL_Program_Uniform_3uiv,
      GL_Program_Uniform_4ui,
      GL_Program_Uniform_4uiv,
      GL_Program_Uniform_1f,
      GL_Program_Uniform_1fv,
      GL_Program_Uniform_2f,
      GL_Program_Uniform_2fv,
      GL_Program_Uniform_3f,
      GL_Program_Uniform_3fv,
      GL_Program_Uniform_4f,
      GL_Program_Uniform_4fv,
      GL_Program_Uniform_Matrix2fv,
      GL_Program_Uniform_Matrix3fv,
      GL_Program_Uniform_Matrix4fv,
      GL_Program_Uniform_1d,
      GL_Program_Uniform_1dv,
      GL_Program_Uniform_2d,
      GL_Program_Uniform_2dv,
      GL_Program_Uniform_3d,
      GL_Program_Uniform_3dv,
      GL_Program_Uniform_4d,
      GL_Program_Uniform_4dv,
      GL_Program_Uniform_Matrix2dv,
      GL_Program_Uniform_Matrix3dv,
      GL_Program_Uniform_Matrix4dv,
      GL_Query_Counter,
      GL_Release_Shader_Compiler,
      GL_Resume_Transform_Feedback,
      GL_Sampler_Parameterf,
      GL_Sampler_Parameterfv,
      GL_Sampler_Parameteri,
      GL_Shader_Source,
      GL_Stencil_Func_Separate,
      GL_Stencil_Mask_Separate,
      GL_Stencil_Op_Separate,
      GL_Texture_Barrier,
      GL_Texture_Buffer,
      GL_Texture_Buffer_Range,
      GL_Texture_Parameterf,
      GL_Texture_Parameterfv,
      GL_Texture_Parameteri,
      GL_Texture_Storage_1D,
      GL_Texture_Storage_2D,
      GL_Texture_Storage_2D_Multisample,
      GL_Texture_Storage_3D,
      GL_Texture_Storage_3D_Multisample,
      GL_Texture_Sub_Image_1D,
      GL_Texture_Sub_Image_2D,
      GL_Texture_Sub_Image_3D,
      GL_Transform_Feedback_Buffer_Base,
      GL_Transform_Feedback_Varyings,
      GL_Uniform_Subroutinesuiv,
      GL_Unmap_Named_Buffer,
      GL_Use_Program,
      GL_Use_Program_Stages,
      GL_Validate_Program,
      GL_Validate_Program_Pipeline,
      GL_Vertex_Array_Attrib_Binding,
      GL_Vertex_Array_Attrib_Format,
      GL_Vertex_Array_Attrib_I_Format,
      GL_Vertex_Array_Attrib_L_Format,
      GL_Vertex_Array_Binding_Divisor,
      GL_Vertex_Array_Element_Buffer,
      GL_Vertex_Array_Vertex_Buffer,
      GL_Vertex_Attrib_4Iiv,
      GL_Vertex_Attrib_I1i,
      GL_Vertex_Attrib_I2i,
      GL_Vertex_Attrib_I2iv,
      GL_Vertex_Attrib_I3i,
      GL_Vertex_Attrib_I3iv,
      GL_Vertex_Attrib_I4i,
      GL_Vertex_Attrib_4Iuiv,
      GL_Vertex_Attrib_I1ui,
      GL_Vertex_Attrib_I2ui,
      GL_Vertex_Attrib_I2uiv,
      GL_Vertex_Attrib_I3ui,
      GL_Vertex_Attrib_I3uiv,
      GL_Vertex_Attrib_I4ui,
      GL_Vertex_Attrib_1s,
      GL_Vertex_Attrib_2s,
      GL_Vertex_Attrib_2sv,
      GL_Vertex_Attrib_3s,
      GL_Vertex_Attrib_3sv,
      GL_Vertex_Attrib_4s,
      GL_Vertex_Attrib_4sv,
      GL_Vertex_Attrib_1f,
      GL_Vertex_Attrib_2f,
      GL_Vertex_Attrib_2fv,
      GL_Vertex_Attrib_3f,
      GL_Vertex_Attrib_3fv,
      GL_Vertex_Attrib_4f,
      GL_Vertex_Attrib_4fv,
      GL_Vertex_Attrib_L1d,
      GL_Vertex_Attrib_L2d,
      GL_Vertex_Attrib_L2dv,
      GL_Vertex_Attrib_L3d,
      GL_Vertex_Attrib_L3dv,
      GL_Vertex_Attrib_L4d,
      GL_Vertex_Attrib_L4dv);

   Function_Map : constant array (Reference_ID) of String_Access :=
     (GL_Active_Shader_Program                             => new String'("glActiveShaderProgram"),
      GL_Attach_Shader                                     => new String'("glAttachShader"),
      GL_Begin_Conditional_Render                          => new String'("glBeginConditionalRender"),
      GL_Begin_Query_Indexed                               => new String'("glBeginQueryIndexed"),
      GL_Begin_Transform_Feedback                          => new String'("glBeginTransformFeedback"),
      GL_Bind_Attrib_Location                              => new String'("glBindAttribLocation"),
      GL_Bind_Buffer                                       => new String'("glBindBuffer"),
      GL_Bind_Buffer_Base                                  => new String'("glBindBufferBase"),
      GL_Bind_Buffer_Range                                 => new String'("glBindBufferRange"),
      GL_Bind_Framebuffer                                  => new String'("glBindFramebuffer"),
      GL_Bind_Program_Pipeline                             => new String'("glBindProgramPipeline"),
      GL_Bind_Renderbuffer                                 => new String'("glBindRenderbuffer"),
      GL_Bind_Sampler                                      => new String'("glBindSampler"),
      GL_Bind_Samplers                                     => new String'("glBindSamplers"),
      GL_Bind_Texture_Unit                                 => new String'("glBindTextureUnit"),
      GL_Bind_Transform_Feedback                           => new String'("glBindTransformFeedback"),
      GL_Bind_Vertex_Array                                 => new String'("glBindVertexArray"),
      GL_Blend_Color                                       => new String'("glBlendColor"),
      GL_Blend_Equation                                    => new String'("glBlendEquation"),
      GL_Blend_Equationi                                   => new String'("glBlendEquationi"),
      GL_Blend_Equation_Separate                           => new String'("glBlendEquationSeparate"),
      GL_Blend_Funci                                       => new String'("glBlendFunci"),
      GL_Blend_Func_Separate                               => new String'("glBlendFuncSeparate"),
      GL_Blit_Named_Framebuffer                            => new String'("glBlitNamedFramebuffer"),
      GL_Check_Named_Framebuffer_Status                    => new String'("glCheckNamedFramebufferStatus"),
      GL_Clamp_Color                                       => new String'("glClampColor"),
      GL_Clear_Named_Framebufferfi                         => new String'("glClearNamedFramebufferfi"),
      GL_Clear_Named_Framebufferfv                         => new String'("glClearNamedFramebufferfv"),
      GL_Clear_Named_Framebufferiv                         => new String'("glClearNamedFramebufferiv"),
      GL_Compile_Shader                                    => new String'("glCompileShader"),
      GL_Compressed_Texture_Sub_Image_1D                   => new String'("glCompressedTextureSubImage1D"),
      GL_Compressed_Texture_Sub_Image_2D                   => new String'("glCompressedTextureSubImage2D"),
      GL_Compressed_Texture_Sub_Image_3D                   => new String'("glCompressedTextureSubImage3D"),
      GL_Copy_Named_Buffer_Sub_Data                        => new String'("glCopyNamedBufferSubData"),
      GL_Copy_Texture_Sub_Image_1D                         => new String'("glCopyTextureSubImage1D"),
      GL_Copy_Texture_Sub_Image_2D                         => new String'("glCopyTextureSubImage2D"),
      GL_Copy_Texture_Sub_Image_3D                         => new String'("glCopyTextureSubImage3D"),
      GL_Create_Buffers                                    => new String'("glCreateBuffers"),
      GL_Create_Framebuffers                               => new String'("glCreateFramebuffers"),
      GL_Create_Program                                    => new String'("glCreateProgram"),
      GL_Create_Program_Pipelines                          => new String'("glCreateProgramPipelines"),
      GL_Create_Queries                                    => new String'("glCreateQueries"),
      GL_Create_Renderbuffers                              => new String'("glCreateRenderbuffers"),
      GL_Create_Samplers                                   => new String'("glCreateSamplers"),
      GL_Create_Shader                                     => new String'("glCreateShader"),
      GL_Create_Shader_Programv                            => new String'("glCreateShaderProgramv"),
      GL_Create_Textures                                   => new String'("glCreateTextures"),
      GL_Create_Transform_Feedbacks                        => new String'("glCreateTransformFeedbacks"),
      GL_Create_Vertex_Arrays                              => new String'("glCreateVertexArrays"),
      GL_Delete_Buffers                                    => new String'("glDeleteBuffers"),
      GL_Delete_Framebuffers                               => new String'("glDeleteFramebuffers"),
      GL_Delete_Program                                    => new String'("glDeleteProgram"),
      GL_Delete_Program_Pipelines                          => new String'("glDeleteProgramPipelines"),
      GL_Delete_Queries                                    => new String'("glDeleteQueries"),
      GL_Delete_Samplers                                   => new String'("glDeleteSamplers"),
      GL_Delete_Shader                                     => new String'("glDeleteShader"),
      GL_Delete_Transform_Feedbacks                        => new String'("glDeleteTransformFeedbacks"),
      GL_Delete_Vertex_Arrays                              => new String'("glDeleteVertexArrays"),
      GL_Disable_Vertex_Array_Attrib                       => new String'("glDisableVertexArrayAttrib"),
      GL_Draw_Arrays_Instanced                             => new String'("glDrawArraysInstanced"),
      GL_Draw_Arrays_Instanced_Base_Instance               => new String'("glDrawArraysInstancedBaseInstance"),
      GL_Draw_Elements_Base_Vertex                         => new String'("glDrawElementsBaseVertex"),
      GL_Draw_Elements_Instanced                           => new String'("glDrawElementsInstanced"),
      GL_Draw_Elements_Instanced_Base_Instance             => new String'("glDrawElementsInstancedBaseInstance"),
      GL_Draw_Elements_Instanced_Base_Vertex               => new String'("glDrawElementsInstancedBaseVertex"),
      GL_Draw_Elements_Instanced_Base_Vertex_Base_Instance => new String'("glDrawElementsInstancedBaseVertexBaseInstance"),
      GL_Draw_Transform_Feedback                           => new String'("glDrawTransformFeedback"),
      GL_Draw_Transform_Feedback_Instanced                 => new String'("glDrawTransformFeedbackInstanced"),
      GL_Draw_Transform_Feedback_Stream                    => new String'("glDrawTransformFeedbackStream"),
      GL_Draw_Transform_Feedback_Stream_Instanced          => new String'("glDrawTransformFeedbackStreamInstanced"),
      GL_Enable_Vertex_Array_Attrib                        => new String'("glEnableVertexArrayAttrib"),
      GL_End_Conditional_Render                            => new String'("glEndConditionalRender"),
      GL_End_Query_Indexed                                 => new String'("glEndQueryIndexed"),
      GL_End_Transform_Feedback                            => new String'("glEndTransformFeedback"),
      GL_Flush_Mapped_Named_Buffer_Range                   => new String'("glFlushMappedNamedBufferRange"),
      GL_Generate_Texture_Mipmap                           => new String'("glGenerateTextureMipmap"),
      GL_Get_Attached_Shaders                              => new String'("glGetAttachedShaders"),
      GL_Get_Attrib_Location                               => new String'("glGetAttribLocation"),
      GL_Get_Named_Buffer_Parameteriv                      => new String'("glGetNamedBufferParameteriv"),
      GL_Get_Named_Buffer_Pointerv                         => new String'("glGetNamedBufferPointerv"),
      GL_Get_Named_Buffer_Sub_Data                         => new String'("glGetNamedBufferSubData"),
      GL_Get_Named_Framebuffer_Parameteriv                 => new String'("glGetNamedFramebufferParameteriv"),
      GL_Get_Named_Renderbuffer_Parameteriv                => new String'("glGetNamedRenderbufferParameteriv"),
      GL_Get_Program_Info_Log                              => new String'("glGetProgramInfoLog"),
      GL_Get_Program_Interfaceiv                           => new String'("glGetProgramInterfaceiv"),
      GL_Get_Programiv                                     => new String'("glGetProgramiv"),
      GL_Get_Program_Pipeline_Info_Log                     => new String'("glGetProgramPipelineInfoLog"),
      GL_Get_Program_Pipelineiv                            => new String'("glGetProgramPipelineiv"),
      GL_Get_Program_Resource_Index                        => new String'("glGetProgramResourceIndex"),
      GL_Get_Program_Resourceiv                            => new String'("glGetProgramResourceiv"),
      GL_Get_Program_Resource_Location                     => new String'("glGetProgramResourceLocation"),
      GL_Get_Program_Resource_Location_Index               => new String'("glGetProgramResourceLocationIndex"),
      GL_Get_Program_Resource_Name                         => new String'("glGetProgramResourceName"),
      GL_Get_Program_Stageiv                               => new String'("glGetProgramStageiv"),
      GL_Get_Query_Indexed                                 => new String'("glGetQueryIndexed"),
      GL_Get_Query_Objectiv                                => new String'("glGetQueryObjectiv"),
      GL_Get_Query_Objectuiv                               => new String'("glGetQueryObjectuiv"),
      GL_Get_Sampler_Parameterfv                           => new String'("glGetSamplerParameterfv"),
      GL_Get_Sampler_Parameteriv                           => new String'("glGetSamplerParameteriv"),
      GL_Get_Shader_Info_Log                               => new String'("glGetShaderInfoLog"),
      GL_Get_Shaderiv                                      => new String'("glGetShaderiv"),
      GL_Get_Shader_Source                                 => new String'("glGetShaderSource"),
      GL_Get_Stringi                                       => new String'("glGetStringi"),
      GL_Get_Texture_Level_Parameteriv                     => new String'("glGetTextureLevelParameteriv"),
      GL_Get_Texture_Parameterfv                           => new String'("glGetTextureParameterfv"),
      GL_Get_Texture_Parameteriv                           => new String'("glGetTextureParameteriv"),
      GL_Get_Uniform_Location                              => new String'("glGetUniformLocation"),
      GL_Get_Uniform_Subroutineuiv                         => new String'("glGetUniformSubroutineuiv"),
      GL_Invalidate_Buffer_Data                            => new String'("glInvalidateBufferData"),
      GL_Invalidate_Buffer_Sub_Data                        => new String'("glInvalidateBufferSubData"),
      GL_Invalidate_Named_Framebuffer_Data                 => new String'("glInvalidateNamedFramebufferData"),
      GL_Invalidate_Named_Framebuffer_Sub_Data             => new String'("glInvalidateNamedFramebufferSubData"),
      GL_Invalidate_Tex_Image                              => new String'("glInvalidateTexImage"),
      GL_Invalidate_Tex_Sub_Image                          => new String'("glInvalidateTexSubImage"),
      GL_Link_Program                                      => new String'("glLinkProgram"),
      GL_Map_Named_Buffer                                  => new String'("glMapNamedBuffer"),
      GL_Map_Named_Buffer_Range                            => new String'("glMapNamedBufferRange"),
      GL_Memory_Barrier                                    => new String'("glMemoryBarrier"),
      GL_Memory_Barrier_By_Region                          => new String'("glMemoryBarrierByRegion"),
      GL_Multi_Draw_Arrays                                 => new String'("glMultiDrawArrays"),
      GL_Multi_Draw_Arrays_Indirect                        => new String'("glMultiDrawArraysIndirect"),
      GL_Multi_Draw_Elements                               => new String'("glMultiDrawElements"),
      GL_Multi_Draw_Elements_Base_Vertex                   => new String'("glMultiDrawElementsBaseVertex"),
      GL_Multi_Draw_Elements_Indirect                      => new String'("glMultiDrawElementsIndirect"),
      GL_Named_Buffer_Data                                 => new String'("glNamedBufferData"),
      GL_Named_Buffer_Storage                              => new String'("glNamedBufferStorage"),
      GL_Named_Buffer_Sub_Data                             => new String'("glNamedBufferSubData"),
      GL_Named_Framebuffer_Draw_Buffer                     => new String'("glNamedFramebufferDrawBuffer"),
      GL_Named_Framebuffer_Draw_Buffers                    => new String'("glNamedFramebufferDrawBuffers"),
      GL_Named_Framebuffer_Parameteri                      => new String'("glNamedFramebufferParameteri"),
      GL_Named_Framebuffer_Read_Buffer                     => new String'("glNamedFramebufferReadBuffer"),
      GL_Named_Framebuffer_Renderbuffer                    => new String'("glNamedFramebufferRenderbuffer"),
      GL_Named_Framebuffer_Texture                         => new String'("glNamedFramebufferTexture"),
      GL_Named_Framebuffer_Texture_Layer                   => new String'("glNamedFramebufferTextureLayer"),
      GL_Named_Renderbuffer_Storage                        => new String'("glNamedRenderbufferStorage"),
      GL_Named_Renderbuffer_Storage_Multisample            => new String'("glNamedRenderbufferStorageMultisample"),
      GL_Pause_Transform_Feedback                          => new String'("glPauseTransformFeedback"),
      GL_Program_Parameteri                                => new String'("glProgramParameteri"),
      GL_Program_Uniform_1i                                => new String'("glProgramUniform1i"),
      GL_Program_Uniform_1iv                               => new String'("glProgramUniform1iv"),
      GL_Program_Uniform_2i                                => new String'("glProgramUniform2i"),
      GL_Program_Uniform_2iv                               => new String'("glProgramUniform2iv"),
      GL_Program_Uniform_3i                                => new String'("glProgramUniform3i"),
      GL_Program_Uniform_3iv                               => new String'("glProgramUniform3iv"),
      GL_Program_Uniform_4i                                => new String'("glProgramUniform4i"),
      GL_Program_Uniform_4iv                               => new String'("glProgramUniform4iv"),
      GL_Program_Uniform_1ui                               => new String'("glProgramUniform1ui"),
      GL_Program_Uniform_1uiv                              => new String'("glProgramUniform1uiv"),
      GL_Program_Uniform_2ui                               => new String'("glProgramUniform2ui"),
      GL_Program_Uniform_2uiv                              => new String'("glProgramUniform2uiv"),
      GL_Program_Uniform_3ui                               => new String'("glProgramUniform3ui"),
      GL_Program_Uniform_3uiv                              => new String'("glProgramUniform3uiv"),
      GL_Program_Uniform_4ui                               => new String'("glProgramUniform4ui"),
      GL_Program_Uniform_4uiv                              => new String'("glProgramUniform4uiv"),
      GL_Program_Uniform_1f                                => new String'("glProgramUniform1f"),
      GL_Program_Uniform_1fv                               => new String'("glProgramUniform1fv"),
      GL_Program_Uniform_2f                                => new String'("glProgramUniform2f"),
      GL_Program_Uniform_2fv                               => new String'("glProgramUniform2fv"),
      GL_Program_Uniform_3f                                => new String'("glProgramUniform3f"),
      GL_Program_Uniform_3fv                               => new String'("glProgramUniform3fv"),
      GL_Program_Uniform_4f                                => new String'("glProgramUniform4f"),
      GL_Program_Uniform_4fv                               => new String'("glProgramUniform4fv"),
      GL_Program_Uniform_Matrix2fv                         => new String'("glProgramUniformMatrix2fv"),
      GL_Program_Uniform_Matrix3fv                         => new String'("glProgramUniformMatrix3fv"),
      GL_Program_Uniform_Matrix4fv                         => new String'("glProgramUniformMatrix4fv"),
      GL_Program_Uniform_1d                                => new String'("glProgramUniform1d"),
      GL_Program_Uniform_1dv                               => new String'("glProgramUniform1dv"),
      GL_Program_Uniform_2d                                => new String'("glProgramUniform2d"),
      GL_Program_Uniform_2dv                               => new String'("glProgramUniform2dv"),
      GL_Program_Uniform_3d                                => new String'("glProgramUniform3d"),
      GL_Program_Uniform_3dv                               => new String'("glProgramUniform3dv"),
      GL_Program_Uniform_4d                                => new String'("glProgramUniform4d"),
      GL_Program_Uniform_4dv                               => new String'("glProgramUniform4dv"),
      GL_Program_Uniform_Matrix2dv                         => new String'("glProgramUniformMatrix2dv"),
      GL_Program_Uniform_Matrix3dv                         => new String'("glProgramUniformMatrix3dv"),
      GL_Program_Uniform_Matrix4dv                         => new String'("glProgramUniformMatrix4dv"),
      GL_Query_Counter                                     => new String'("glQueryCounter"),
      GL_Release_Shader_Compiler                           => new String'("glReleaseShaderCompiler"),
      GL_Resume_Transform_Feedback                         => new String'("glResumeTransformFeedback"),
      GL_Sampler_Parameterf                                => new String'("glSamplerParameterf"),
      GL_Sampler_Parameterfv                               => new String'("glSamplerParameterfv"),
      GL_Sampler_Parameteri                                => new String'("glSamplerParameteri"),
      GL_Shader_Source                                     => new String'("glShaderSource"),
      GL_Stencil_Func_Separate                             => new String'("glStencilFuncSeparate"),
      GL_Stencil_Mask_Separate                             => new String'("glStencilMaskSeparate"),
      GL_Stencil_Op_Separate                               => new String'("glStencilOpSeparate"),
      GL_Texture_Barrier                                   => new String'("glTextureBarrier"),
      GL_Texture_Buffer                                    => new String'("glTextureBuffer"),
      GL_Texture_Buffer_Range                              => new String'("glTextureBufferRange"),
      GL_Texture_Parameterf                                => new String'("glTextureParameterf"),
      GL_Texture_Parameterfv                               => new String'("glTextureParameterfv"),
      GL_Texture_Parameteri                                => new String'("glTextureParameteri"),
      GL_Texture_Storage_1D                                => new String'("glTextureStorage1D"),
      GL_Texture_Storage_2D                                => new String'("glTextureStorage2D"),
      GL_Texture_Storage_2D_Multisample                    => new String'("glTextureStorage2DMultisample"),
      GL_Texture_Storage_3D                                => new String'("glTextureStorage3D"),
      GL_Texture_Storage_3D_Multisample                    => new String'("glTextureStorage3DMultisample"),
      GL_Texture_Sub_Image_1D                              => new String'("glTextureSubImage1D"),
      GL_Texture_Sub_Image_2D                              => new String'("glTextureSubImage2D"),
      GL_Texture_Sub_Image_3D                              => new String'("glTextureSubImage3D"),
      GL_Transform_Feedback_Buffer_Base                    => new String'("glTransformFeedbackBufferBase"),
      GL_Transform_Feedback_Varyings                       => new String'("glTransformFeedbackVaryings"),
      GL_Uniform_Subroutinesuiv                            => new String'("glUniformSubroutinesuiv"),
      GL_Unmap_Named_Buffer                                => new String'("glUnmapNamedBuffer"),
      GL_Use_Program                                       => new String'("glUseProgram"),
      GL_Use_Program_Stages                                => new String'("glUseProgramStages"),
      GL_Validate_Program                                  => new String'("glValidateProgram"),
      GL_Validate_Program_Pipeline                         => new String'("glValidateProgramPipeline"),
      GL_Vertex_Array_Attrib_Binding                       => new String'("glVertexArrayAttribBinding"),
      GL_Vertex_Array_Attrib_Format                        => new String'("glVertexArrayAttribFormat"),
      GL_Vertex_Array_Attrib_I_Format                      => new String'("glVertexArrayAttribIFormat"),
      GL_Vertex_Array_Attrib_L_Format                      => new String'("glVertexArrayAttribLFormat"),
      GL_Vertex_Array_Binding_Divisor                      => new String'("glVertexArrayBindingDivisor"),
      GL_Vertex_Array_Element_Buffer                       => new String'("glVertexArrayElementBuffer"),
      GL_Vertex_Array_Vertex_Buffer                        => new String'("glVertexArrayVertexBuffer"),
      GL_Vertex_Attrib_4Iiv                                => new String'("glVertexAttrib4Iiv"),
      GL_Vertex_Attrib_I1i                                 => new String'("glVertexAttribI1i"),
      GL_Vertex_Attrib_I2i                                 => new String'("glVertexAttribI2i"),
      GL_Vertex_Attrib_I2iv                                => new String'("glVertexAttribI2iv"),
      GL_Vertex_Attrib_I3i                                 => new String'("glVertexAttribI3i"),
      GL_Vertex_Attrib_I3iv                                => new String'("glVertexAttribI3iv"),
      GL_Vertex_Attrib_I4i                                 => new String'("glVertexAttribI4i"),
      GL_Vertex_Attrib_4Iuiv                               => new String'("glVertexAttrib4Iuiv"),
      GL_Vertex_Attrib_I1ui                                => new String'("glVertexAttribI1ui"),
      GL_Vertex_Attrib_I2ui                                => new String'("glVertexAttribI2ui"),
      GL_Vertex_Attrib_I2uiv                               => new String'("glVertexAttribI2uiv"),
      GL_Vertex_Attrib_I3ui                                => new String'("glVertexAttribI3ui"),
      GL_Vertex_Attrib_I3uiv                               => new String'("glVertexAttribI3uiv"),
      GL_Vertex_Attrib_I4ui                                => new String'("glVertexAttribI4ui"),
      GL_Vertex_Attrib_1s                                  => new String'("glVertexAttrib1s"),
      GL_Vertex_Attrib_2s                                  => new String'("glVertexAttrib2s"),
      GL_Vertex_Attrib_2sv                                 => new String'("glVertexAttrib2sv"),
      GL_Vertex_Attrib_3s                                  => new String'("glVertexAttrib3s"),
      GL_Vertex_Attrib_3sv                                 => new String'("glVertexAttrib3sv"),
      GL_Vertex_Attrib_4s                                  => new String'("glVertexAttrib4s"),
      GL_Vertex_Attrib_4sv                                 => new String'("glVertexAttrib4sv"),
      GL_Vertex_Attrib_1f                                  => new String'("glVertexAttrib1f"),
      GL_Vertex_Attrib_2f                                  => new String'("glVertexAttrib2f"),
      GL_Vertex_Attrib_2fv                                 => new String'("glVertexAttrib2fv"),
      GL_Vertex_Attrib_3f                                  => new String'("glVertexAttrib3f"),
      GL_Vertex_Attrib_3fv                                 => new String'("glVertexAttrib3fv"),
      GL_Vertex_Attrib_4f                                  => new String'("glVertexAttrib4f"),
      GL_Vertex_Attrib_4fv                                 => new String'("glVertexAttrib4fv"),
      GL_Vertex_Attrib_L1d                                 => new String'("glVertexAttribL1d"),
      GL_Vertex_Attrib_L2d                                 => new String'("glVertexAttribL2d"),
      GL_Vertex_Attrib_L2dv                                => new String'("glVertexAttribL2dv"),
      GL_Vertex_Attrib_L3d                                 => new String'("glVertexAttribL3d"),
      GL_Vertex_Attrib_L3dv                                => new String'("glVertexAttribL3dv"),
      GL_Vertex_Attrib_L4d                                 => new String'("glVertexAttribL4d"),
      GL_Vertex_Attrib_L4dv                                => new String'("glVertexAttribL4dv"));

end GL.Functions;
