name = "orka_plugin_terrain"
description = "Orka plug-in for adaptive tessellated flattened spheroids"
version = "1.0.0"
website = "https://github.com/onox/orka"
licenses = "Apache-2.0 AND MIT"
tags = ["terrain", "orka"]

authors = ["onox", "Jonathan Dupuy"]
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]

[build-switches]
validation.compile_checks = "warnings"
"*".style_checks = ["-gnatygAO-Is"]

[[depends-on]]
orka_transforms = "^1.0.0"
orka = "~0.2.0"

[[pins]]
orka = { path = "../orka" }
orka_transforms = { path = "../orka_transforms" }
