name = "orka_plugin_archives"
description = "Orka plug-in to load resources from Zip archives"
version = "1.0.0"
website = "https://github.com/onox/orka"
licenses = "Apache-2.0"
tags = ["orka", "zip", "dcf"]

authors = ["onox"]
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]

[build-switches]
validation.compile_checks = "warnings"
"*".style_checks = ["-gnatygAO-Is"]

[[depends-on]]
dcf = "^2.0.3"
orka = "~0.2.0"

[[pins]]
orka = { path = "../orka" }
