name = "orka_tensors_cpu"
description = "Tensors using SIMD instructions on the CPU"
version = "1.0.0"
website = "https://github.com/onox/orka"
licenses = "Apache-2.0"
tags = ["orka", "math", "vector", "matrix", "ndarray", "tensor", "numpy", "random", "statistics", "leastsquares", "linearalgebra", "linalg", "simd"]

authors = ["onox"]
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]

[build-switches]
validation.compile_checks = "warnings"
"*".style_checks = ["-gnatygAOM120-Is"]
"*".ada_version = "Ada2022"

[gpr-externals]
ORKA_TENSORS_CPU_SIMD_TYPE = ["SSE4", "AVX", "AVX2"]

[gpr-set-externals]
ORKA_TENSORS_CPU_SIMD_TYPE = "SSE4"

[[depends-on]]
orka_numerics = "~1.0.0"
orka_simd = "~1.0.0"
orka_types = "~1.0.0"

[[pins]]
orka_numerics = { path = "../orka_numerics" }
orka_simd = { path = "../orka_simd" }
orka_types = { path = "../orka_types" }
