name = "orka_egl"
description = "Ada 2012 bindings for EGL"
version = "1.0.0"
website = "https://github.com/onox/orka"
licenses = "Apache-2.0"
tags = ["egl", "opengl", "orka"]

executables = ["orka_egl_info"]

project-files = ["orka_egl.gpr", "orka_egl_info.gpr"]

authors = ["onox"]
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]

configuration.disabled = true

[available.'case(os)']
linux = true
'...' = false

[[depends-on]]
libegl = "^1.3.2"
