name: Build

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  build:
    name: Building on ${{matrix.os}} using ${{matrix.compiler}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [fsf]
    steps:
    - uses: actions/checkout@v2

    - name: Install toolchain
      uses: ada-actions/toolchain@ce2021
      with:
        distrib: ${{matrix.compiler}}
        target: native

    - name: Install Alire
      uses: alire-project/setup-alire@latest-stable

    - name: Run tests
      run: make tests

    - name: Generate coverage
      run: make coverage
