name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: ${{matrix.experimental}}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        experimental: [false]
        include:
          - os: windows-latest
            experimental: true
    steps:
    - uses: actions/checkout@v2
    - uses: alire-project/setup-alire@v1

    - name: Run tests
      run: make tests

    - name: Install lcov
      run: |
        sudo apt update
        sudo apt install lcov
      continue-on-error: true
      if: ${{ matrix.os != 'windows-latest'}}

    - name: Generate coverage
      run: make coverage
      continue-on-error: true
      if: ${{ matrix.os != 'windows-latest'}}
