name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  build:
    name: Testing on ${{matrix.os}} using ${{matrix.compiler}}
    runs-on: ${{matrix.os}}
    continue-on-error: ${{matrix.experimental}}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        compiler: [fsf, community]
        experimental: [false]
        exclude:
          - os: ubuntu-latest
            compiler: fsf
        include:
          - os: windows-latest
            compiler: community
            experimental: true
    steps:
    - uses: actions/checkout@v2

    - name: Install toolchain
      uses: ada-actions/toolchain@ce2021
      with:
        distrib: ${{matrix.compiler}}
        target: native

    - name: Install Alire
      uses: alire-project/setup-alire@v1
      with:
        toolchain: "gnat_external"

    - name: Run tests
      run: make tests

    - name: Install lcov
      run: |
        sudo apt update
        sudo apt install lcov
      continue-on-error: true
      if: ${{ matrix.os != 'windows-latest'}}

    - name: Generate coverage
      run: make coverage
      continue-on-error: true
      if: ${{ matrix.os != 'windows-latest'}}
